apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 4
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: app
          image: dfeng007/website:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
